In [508]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [509]:
filename = 'nba_injuries_2016-2018.csv'

In [510]:
injuries_df = pd.read_csv(filename, parse_dates=['Date'])
injuries_df

,Date,Team,Relinquised,Notes
0,2016-10-26,Grizzlies,Tony Allen,right knee injury (DTD)
1,2016-10-26,Hawks,Mike Scott,left knee injury (DTD)
2,2016-10-26,Pacers,Aaron Brooks,sore knee (DTD)
3,2016-10-26,Raptors,Lucas Nogueira,sore/sprained left ankle (DTD)
4,2016-10-27,Blazers,Meyers Leonard,DNP (P)
5,2016-10-28,Knicks,Ron Baker,sore ankle (DTD)
6,2016-10-28,Pacers,Rodney Stuckey,sore right hamstring (DTD)
7,2016-10-29,Hornets,Jeremy Lamb,strained left hamstring (DTD)
8,2016-10-29,Nets,Brook Lopez,rest (DTD)
9,2016-10-29,Nets,Greivis Vasquez,sore right ankle (DTD)
10,2016-10-29,Spurs,(William) Tony Parker,knee injury / rest (DTD)
11,2016-10-29,Warriors,Patrick McCaw,sore left ankle (DTD)
12,2016-10-30,Mavericks,Dirk Nowitzki,illness (DTD)
13,2016-10-31,Timberwolves,Ricky Rubio,sprained right elbow (DTD)
14,2016-11-01,Bulls,Doug McDermott,concussion (DTD)
15,2016-11-01,Bulls,Michael Carter-Williams,bone bruise in left knee (out indefinitely)
16,2016-11-01,Grizzlies,Marc Gasol,rest (DTD)
17,2016-11-01,Grizzlies,Mike Conley Jr.,rest (DTD)
18,2016-11-01,Jazz,Alec Burks,arthrosopic surgery on left ankle (out indefin...
19,2016-11-01,Jazz,Boris Diaw,bruised right leg (DTD)
20,2016-11-01,Nuggets,Will Barton,sore/sprained left ankle (DTD)
21,2016-11-02,76ers,Joel Embiid,rehab of foot injury (DTD)
22,2016-11-02,Celtics,Jae Crowder,sprained left ankle (DTD)
23,2016-11-02,Grizzlies,Jarell Martin,sore foot (DTD)
24,2016-11-02,Hornets,Christian Wood,strep throat (DTD)
25,2016-11-02,Jazz,Boris Diaw,bruised right leg (DTD)
26,2016-11-02,Mavericks,Wesley Matthews / Wes Matthews Jr.,sore foot (DTD)
27,2016-11-02,Nets,Jeremy Lin,strained left hamstring (DTD)
28,2016-11-02,Pelicans,Dante Cunningham,sore hip (DTD)
29,2016-11-03,Kings,Anthony Tolliver,sprained right knee (DTD)
...,...,...,...,...
1403,2018-04-09,Clippers,Louis Williams / Lou Williams,sprained right ankle (out for season)
1404,2018-04-09,Grizzlies,Marc Gasol,rest (DTD)
1405,2018-04-09,Hawks,Malcolm Delaney,arthroscopic surgery on left ankle (out for se...
1406,2018-04-09,Kings,Frank Mason,partially torn plantar fascia in left foot (ou...
1407,2018-04-09,Nets,Joe Harris,sprained left ankle (out for season)
1408,2018-04-10,Mavericks,Doug McDermott,elbow injury (out for season)
1409,2018-04-10,Rockets,Luc Richard Mbah a Moute / Luc Mbah a Moute,dislocated right shoulder (DTD)
1410,2018-04-10,Suns,Troy Daniels,sprained right ankle (DTD)
1411,2018-04-10,Thunder,Alex Abrines,concussion (DTD)
1412,2018-04-11,76ers,J.J. Redick,tightness in lower back (DTD)
1413,2018-04-11,Grizzlies,Marc Gasol,rest (DTD)
1414,2018-04-11,Knicks,Courtney Lee,sprained left ankle (out for season)
1415,2018-04-11,Pistons,Jameer Nelson,illness (out for season)
1416,2018-04-11,Rockets,Chris Paul,rest (DTD)
1417,2018-04-11,Rockets,Clint Capela,hand injury (DTD)
1418,2018-04-11,Rockets,Eric Gordon,ankle injury / rest (DTD)
1419,2018-04-11,Rockets,James Harden,rest (DTD)
1420,2018-04-12,Hawks,DeAndre' Bembry / DeAndre Bembry,fractured right wrist (out for season)
1421,2018-04-18,Timberwolves,Justin Patton,surgery on left foot (out for season)
1422,2018-04-20,Pacers,Joe Young,illness (DTD)
1423,2018-04-23,Timberwolves,Tyus Jones,sore right knee (DTD)
1424,2018-04-26,Nuggets,Mason Plumlee,surgery to repair core muscle injury
1425,2018-04-27,Wizards,Otto Porter Jr.,surgery on left leg to remove blood around a c...
1426,2018-04-30,Celtics,Jaylen Brown,strained right hamstring (DTD)
1427,2018-05-07,Jazz,Dante Exum,strained left hamstring (out for season)
1428,2018-05-09,Celtics,Shane Larkin,sprained left shoulder (out for season)
1429,2018-05-09,Thunder,Paul George,arthroscopic surgery on right knee (out indefi...
1430,2018-05-22,Warriors,Andre Iguodala,bruised left leg (DTD)
1431,2018-05-25,Rockets,Chris Paul,strained right hamstring (out for season)
1432,2018-05-26,Cavaliers,Kevin Love,concussion (DTD)

In [511]:
injured_players = injuries_df['Relinquised'].drop_duplicates()
injured_players

0                                     Tony Allen
1                                     Mike Scott
2                                   Aaron Brooks
3                                 Lucas Nogueira
4                                 Meyers Leonard
5                                      Ron Baker
6                                 Rodney Stuckey
7                                    Jeremy Lamb
8                                    Brook Lopez
9                                Greivis Vasquez
10                         (William) Tony Parker
11                                 Patrick McCaw
12                                 Dirk Nowitzki
13                                   Ricky Rubio
14                                Doug McDermott
15                       Michael Carter-Williams
16                                    Marc Gasol
17                               Mike Conley Jr.
18                                    Alec Burks
19                                    Boris Diaw
20                                   Will Barton
21                                   Joel Embiid
22                                   Jae Crowder
23                                 Jarell Martin
24                                Christian Wood
26            Wesley Matthews / Wes Matthews Jr.
27                                    Jeremy Lin
28                              Dante Cunningham
29                              Anthony Tolliver
32                              Lance Stephenson
                          ...
1208                               Channing Frye
1212                          Antonius Cleveland
1230                                Daniel Theis
1232                                   Josh Hart
1241                                Emeka Okafor
1260                           Terrance Ferguson
1261                                  Cedi Osman
1271                               Jaylen Morris
1280                                  Kyle Kuzma
1281            Domantas Sabonis / Domas Sabonis
1283    Timothe Luwawu / Timothe Luwawu-Cabarrot
1293                                  Tyronn Lue
1305                            Antonio Blakeney
1311                              Shabazz Napier
1324                              Damyean Dotson
1325                                Kyle O'Quinn
1329                Edrice Adebayo / Bam Adebayo
1330                               Dwight Powell
1337                               Chris Boucher
1347                  Wesley Iwundu / Wes Iwundu
1367                             Frank Ntilikina
1369                              MarShon Brooks
1370                                Dwayne Bacon
1381                             Skal Labissiere
1395                                   Ian Clark
1398                            Shabazz Muhammad
1401                                Josh Jackson
1411                                Alex Abrines
1423                                  Tyus Jones
1424                               Mason Plumlee
Name: Relinquised, Length: 416, dtype: object

In [512]:
sep_by_slash = lambda x: pd.Series([i for i in x.split('/')])
injured_players = injured_players.apply(sep_by_slash)
injured_players

                            0                         1    2
0                  Tony Allen                       NaN  NaN
1                  Mike Scott                       NaN  NaN
2                Aaron Brooks                       NaN  NaN
3              Lucas Nogueira                       NaN  NaN
4              Meyers Leonard                       NaN  NaN
5                   Ron Baker                       NaN  NaN
6              Rodney Stuckey                       NaN  NaN
7                 Jeremy Lamb                       NaN  NaN
8                 Brook Lopez                       NaN  NaN
9             Greivis Vasquez                       NaN  NaN
10      (William) Tony Parker                       NaN  NaN
11              Patrick McCaw                       NaN  NaN
12              Dirk Nowitzki                       NaN  NaN
13                Ricky Rubio                       NaN  NaN
14             Doug McDermott                       NaN  NaN
15    Michael Carter-Williams                       NaN  NaN
16                 Marc Gasol                       NaN  NaN
17            Mike Conley Jr.                       NaN  NaN
18                 Alec Burks                       NaN  NaN
19                 Boris Diaw                       NaN  NaN
20                Will Barton                       NaN  NaN
21                Joel Embiid                       NaN  NaN
22                Jae Crowder                       NaN  NaN
23              Jarell Martin                       NaN  NaN
24             Christian Wood                       NaN  NaN
26           Wesley Matthews           Wes Matthews Jr.  NaN
27                 Jeremy Lin                       NaN  NaN
28           Dante Cunningham                       NaN  NaN
29           Anthony Tolliver                       NaN  NaN
32           Lance Stephenson                       NaN  NaN
...                       ...                       ...  ...
1208            Channing Frye                       NaN  NaN
1212       Antonius Cleveland                       NaN  NaN
1230             Daniel Theis                       NaN  NaN
1232                Josh Hart                       NaN  NaN
1241             Emeka Okafor                       NaN  NaN
1260        Terrance Ferguson                       NaN  NaN
1261               Cedi Osman                       NaN  NaN
1271            Jaylen Morris                       NaN  NaN
1280               Kyle Kuzma                       NaN  NaN
1281        Domantas Sabonis              Domas Sabonis  NaN
1283          Timothe Luwawu    Timothe Luwawu-Cabarrot  NaN
1293               Tyronn Lue                       NaN  NaN
1305         Antonio Blakeney                       NaN  NaN
1311           Shabazz Napier                       NaN  NaN
1324           Damyean Dotson                       NaN  NaN
1325             Kyle O'Quinn                       NaN  NaN
1329          Edrice Adebayo                Bam Adebayo  NaN
1330            Dwight Powell                       NaN  NaN
1337            Chris Boucher                       NaN  NaN
1347           Wesley Iwundu                 Wes Iwundu  NaN
1367          Frank Ntilikina                       NaN  NaN
1369           MarShon Brooks                       NaN  NaN
1370             Dwayne Bacon                       NaN  NaN
1381          Skal Labissiere                       NaN  NaN
1395                Ian Clark                       NaN  NaN
1398         Shabazz Muhammad                       NaN  NaN
1401             Josh Jackson                       NaN  NaN
1411             Alex Abrines                       NaN  NaN
1423               Tyus Jones                       NaN  NaN
1424            Mason Plumlee                       NaN  NaN

[416 rows x 3 columns]

In [513]:
sep_by_space = lambda x: pd.Series([i for i in x.split(' ')])
updated_injured_players = injured_players[0].apply(sep_by_space)
updated_injured_players

              0                1       2    3    4    5
0          Tony            Allen     NaN  NaN  NaN  NaN
1          Mike            Scott     NaN  NaN  NaN  NaN
2         Aaron           Brooks     NaN  NaN  NaN  NaN
3         Lucas         Nogueira     NaN  NaN  NaN  NaN
4        Meyers          Leonard     NaN  NaN  NaN  NaN
5           Ron            Baker     NaN  NaN  NaN  NaN
6        Rodney          Stuckey     NaN  NaN  NaN  NaN
7        Jeremy             Lamb     NaN  NaN  NaN  NaN
8         Brook            Lopez     NaN  NaN  NaN  NaN
9       Greivis          Vasquez     NaN  NaN  NaN  NaN
10    (William)             Tony  Parker  NaN  NaN  NaN
11      Patrick            McCaw     NaN  NaN  NaN  NaN
12         Dirk         Nowitzki     NaN  NaN  NaN  NaN
13        Ricky            Rubio     NaN  NaN  NaN  NaN
14         Doug        McDermott     NaN  NaN  NaN  NaN
15      Michael  Carter-Williams     NaN  NaN  NaN  NaN
16         Marc            Gasol     NaN  NaN  NaN  NaN
17         Mike           Conley     Jr.  NaN  NaN  NaN
18         Alec            Burks     NaN  NaN  NaN  NaN
19        Boris             Diaw     NaN  NaN  NaN  NaN
20         Will           Barton     NaN  NaN  NaN  NaN
21         Joel           Embiid     NaN  NaN  NaN  NaN
22          Jae          Crowder     NaN  NaN  NaN  NaN
23       Jarell           Martin     NaN  NaN  NaN  NaN
24    Christian             Wood     NaN  NaN  NaN  NaN
26       Wesley         Matthews          NaN  NaN  NaN
27       Jeremy              Lin     NaN  NaN  NaN  NaN
28        Dante       Cunningham     NaN  NaN  NaN  NaN
29      Anthony         Tolliver     NaN  NaN  NaN  NaN
32        Lance       Stephenson     NaN  NaN  NaN  NaN
...         ...              ...     ...  ...  ...  ...
1208   Channing             Frye     NaN  NaN  NaN  NaN
1212   Antonius        Cleveland     NaN  NaN  NaN  NaN
1230     Daniel            Theis     NaN  NaN  NaN  NaN
1232       Josh             Hart     NaN  NaN  NaN  NaN
1241      Emeka           Okafor     NaN  NaN  NaN  NaN
1260   Terrance         Ferguson     NaN  NaN  NaN  NaN
1261       Cedi            Osman     NaN  NaN  NaN  NaN
1271     Jaylen           Morris     NaN  NaN  NaN  NaN
1280       Kyle            Kuzma     NaN  NaN  NaN  NaN
1281   Domantas          Sabonis          NaN  NaN  NaN
1283    Timothe           Luwawu          NaN  NaN  NaN
1293     Tyronn              Lue     NaN  NaN  NaN  NaN
1305    Antonio         Blakeney     NaN  NaN  NaN  NaN
1311    Shabazz           Napier     NaN  NaN  NaN  NaN
1324    Damyean           Dotson     NaN  NaN  NaN  NaN
1325       Kyle          O'Quinn     NaN  NaN  NaN  NaN
1329     Edrice          Adebayo          NaN  NaN  NaN
1330     Dwight           Powell     NaN  NaN  NaN  NaN
1337      Chris          Boucher     NaN  NaN  NaN  NaN
1347     Wesley           Iwundu          NaN  NaN  NaN
1367      Frank        Ntilikina     NaN  NaN  NaN  NaN
1369    MarShon           Brooks     NaN  NaN  NaN  NaN
1370     Dwayne            Bacon     NaN  NaN  NaN  NaN
1381       Skal       Labissiere     NaN  NaN  NaN  NaN
1395        Ian            Clark     NaN  NaN  NaN  NaN
1398    Shabazz         Muhammad     NaN  NaN  NaN  NaN
1401       Josh          Jackson     NaN  NaN  NaN  NaN
1411       Alex          Abrines     NaN  NaN  NaN  NaN
1423       Tyus            Jones     NaN  NaN  NaN  NaN
1424      Mason          Plumlee     NaN  NaN  NaN  NaN

[416 rows x 6 columns]

In [514]:
injured_players

                            0                         1    2
0                  Tony Allen                       NaN  NaN
1                  Mike Scott                       NaN  NaN
2                Aaron Brooks                       NaN  NaN
3              Lucas Nogueira                       NaN  NaN
4              Meyers Leonard                       NaN  NaN
5                   Ron Baker                       NaN  NaN
6              Rodney Stuckey                       NaN  NaN
7                 Jeremy Lamb                       NaN  NaN
8                 Brook Lopez                       NaN  NaN
9             Greivis Vasquez                       NaN  NaN
10      (William) Tony Parker                       NaN  NaN
11              Patrick McCaw                       NaN  NaN
12              Dirk Nowitzki                       NaN  NaN
13                Ricky Rubio                       NaN  NaN
14             Doug McDermott                       NaN  NaN
15    Michael Carter-Williams                       NaN  NaN
16                 Marc Gasol                       NaN  NaN
17            Mike Conley Jr.                       NaN  NaN
18                 Alec Burks                       NaN  NaN
19                 Boris Diaw                       NaN  NaN
20                Will Barton                       NaN  NaN
21                Joel Embiid                       NaN  NaN
22                Jae Crowder                       NaN  NaN
23              Jarell Martin                       NaN  NaN
24             Christian Wood                       NaN  NaN
26           Wesley Matthews           Wes Matthews Jr.  NaN
27                 Jeremy Lin                       NaN  NaN
28           Dante Cunningham                       NaN  NaN
29           Anthony Tolliver                       NaN  NaN
32           Lance Stephenson                       NaN  NaN
...                       ...                       ...  ...
1208            Channing Frye                       NaN  NaN
1212       Antonius Cleveland                       NaN  NaN
1230             Daniel Theis                       NaN  NaN
1232                Josh Hart                       NaN  NaN
1241             Emeka Okafor                       NaN  NaN
1260        Terrance Ferguson                       NaN  NaN
1261               Cedi Osman                       NaN  NaN
1271            Jaylen Morris                       NaN  NaN
1280               Kyle Kuzma                       NaN  NaN
1281        Domantas Sabonis              Domas Sabonis  NaN
1283          Timothe Luwawu    Timothe Luwawu-Cabarrot  NaN
1293               Tyronn Lue                       NaN  NaN
1305         Antonio Blakeney                       NaN  NaN
1311           Shabazz Napier                       NaN  NaN
1324           Damyean Dotson                       NaN  NaN
1325             Kyle O'Quinn                       NaN  NaN
1329          Edrice Adebayo                Bam Adebayo  NaN
1330            Dwight Powell                       NaN  NaN
1337            Chris Boucher                       NaN  NaN
1347           Wesley Iwundu                 Wes Iwundu  NaN
1367          Frank Ntilikina                       NaN  NaN
1369           MarShon Brooks                       NaN  NaN
1370             Dwayne Bacon                       NaN  NaN
1381          Skal Labissiere                       NaN  NaN
1395                Ian Clark                       NaN  NaN
1398         Shabazz Muhammad                       NaN  NaN
1401             Josh Jackson                       NaN  NaN
1411             Alex Abrines                       NaN  NaN
1423               Tyus Jones                       NaN  NaN
1424            Mason Plumlee                       NaN  NaN

[416 rows x 3 columns]

In [515]:
updated_injured_players[updated_injured_players[2].notnull()]

              0            1       2    3      4    5
10    (William)         Tony  Parker  NaN    NaN  NaN
17         Mike       Conley     Jr.  NaN    NaN  NaN
26       Wesley     Matthews          NaN    NaN  NaN
36        Larry        Nance     Jr.  NaN    NaN  NaN
42         Jose         Juan   Barea         NaN  NaN
72       Alexis       Ajinca          NaN    NaN  NaN
95       Gerald    Henderson     (b)  NaN    NaN  NaN
104     Juancho  Hernangomez          NaN    NaN  NaN
163     Emanuel     Ginobili          NaN    NaN  NaN
174      Justin     Hamilton     (b)  NaN    NaN  NaN
177        Zaur     Pachulia          NaN    NaN  NaN
189         Luc      Richard    Mbah    a  Moute
217         Tim     Hardaway     Jr.  NaN    NaN  NaN
253     Matthew  Dellavedova          NaN    NaN  NaN
259     Maurice        Ndour          NaN    NaN  NaN
262        Mike     Dunleavy     Jr.  NaN    NaN  NaN
311     Maurice     Harkless          NaN    NaN  NaN
317     Patrick        Mills          NaN    NaN  NaN
330          Ed        Davis     (a)  NaN    NaN  NaN
365      Gerald        Green     (b)  NaN    NaN  NaN
527      Johnny     O'Bryant     III  NaN    NaN  NaN
595       Glenn     Robinson     III  NaN    NaN  NaN
620   Raulzinho         Neto          NaN    NaN  NaN
702        John         Wall     (a)  NaN    NaN  NaN
740     Sheldon    McClellan          NaN    NaN  NaN
762      Walter      Tavares          NaN    NaN  NaN
782    DeAndre'       Bembry          NaN    NaN  NaN
783      Ogugua      Anunoby          NaN    NaN  NaN
822       Milos     Teodosic          NaN    NaN  NaN
860       Wayne       Selden     Jr.  NaN    NaN  NaN
929        Zhou           Qi          NaN    NaN  NaN
935        John      Collins     (b)  NaN    NaN  NaN
970      Yakuba     Ouattara          NaN    NaN  NaN
1010       Otto       Porter     Jr.  NaN    NaN  NaN
1012      Louis     Williams          NaN    NaN  NaN
1013     Wesley      Johnson          NaN    NaN  NaN
1040     Reggie      Jackson     (b)  NaN    NaN  NaN
1062    Derrick       Walton     Jr.  NaN    NaN  NaN
1185  Johnathan       Motley          NaN    NaN  NaN
1281   Domantas      Sabonis          NaN    NaN  NaN
1283    Timothe       Luwawu          NaN    NaN  NaN
1329     Edrice      Adebayo          NaN    NaN  NaN
1347     Wesley       Iwundu          NaN    NaN  NaN

In [516]:
updated_injured_players[updated_injured_players[0].str.contains("(", regex=False)]

            0     1       2    3    4    5
10  (William)  Tony  Parker  NaN  NaN  NaN

In [517]:
test = updated_injured_players.replace(r'^\s*$', '0', regex=True)
test = test.replace(np.nan, '0', regex=True)
test = test.reset_index()
test = test[[0,1,2,3,4,5]]
test

             0                1       2  3  4  5
0         Tony            Allen       0  0  0  0
1         Mike            Scott       0  0  0  0
2        Aaron           Brooks       0  0  0  0
3        Lucas         Nogueira       0  0  0  0
4       Meyers          Leonard       0  0  0  0
5          Ron            Baker       0  0  0  0
6       Rodney          Stuckey       0  0  0  0
7       Jeremy             Lamb       0  0  0  0
8        Brook            Lopez       0  0  0  0
9      Greivis          Vasquez       0  0  0  0
10   (William)             Tony  Parker  0  0  0
11     Patrick            McCaw       0  0  0  0
12        Dirk         Nowitzki       0  0  0  0
13       Ricky            Rubio       0  0  0  0
14        Doug        McDermott       0  0  0  0
15     Michael  Carter-Williams       0  0  0  0
16        Marc            Gasol       0  0  0  0
17        Mike           Conley     Jr.  0  0  0
18        Alec            Burks       0  0  0  0
19       Boris             Diaw       0  0  0  0
20        Will           Barton       0  0  0  0
21        Joel           Embiid       0  0  0  0
22         Jae          Crowder       0  0  0  0
23      Jarell           Martin       0  0  0  0
24   Christian             Wood       0  0  0  0
25      Wesley         Matthews       0  0  0  0
26      Jeremy              Lin       0  0  0  0
27       Dante       Cunningham       0  0  0  0
28     Anthony         Tolliver       0  0  0  0
29       Lance       Stephenson       0  0  0  0
..         ...              ...     ... .. .. ..
386   Channing             Frye       0  0  0  0
387   Antonius        Cleveland       0  0  0  0
388     Daniel            Theis       0  0  0  0
389       Josh             Hart       0  0  0  0
390      Emeka           Okafor       0  0  0  0
391   Terrance         Ferguson       0  0  0  0
392       Cedi            Osman       0  0  0  0
393     Jaylen           Morris       0  0  0  0
394       Kyle            Kuzma       0  0  0  0
395   Domantas          Sabonis       0  0  0  0
396    Timothe           Luwawu       0  0  0  0
397     Tyronn              Lue       0  0  0  0
398    Antonio         Blakeney       0  0  0  0
399    Shabazz           Napier       0  0  0  0
400    Damyean           Dotson       0  0  0  0
401       Kyle          O'Quinn       0  0  0  0
402     Edrice          Adebayo       0  0  0  0
403     Dwight           Powell       0  0  0  0
404      Chris          Boucher       0  0  0  0
405     Wesley           Iwundu       0  0  0  0
406      Frank        Ntilikina       0  0  0  0
407    MarShon           Brooks       0  0  0  0
408     Dwayne            Bacon       0  0  0  0
409       Skal       Labissiere       0  0  0  0
410        Ian            Clark       0  0  0  0
411    Shabazz         Muhammad       0  0  0  0
412       Josh          Jackson       0  0  0  0
413       Alex          Abrines       0  0  0  0
414       Tyus            Jones       0  0  0  0
415      Mason          Plumlee       0  0  0  0

[416 rows x 6 columns]

In [518]:
test[test[2].str.contains("(", regex=False)]

          0          1    2  3  4  5
75   Gerald  Henderson  (b)  0  0  0
121  Justin   Hamilton  (b)  0  0  0
200      Ed      Davis  (a)  0  0  0
211  Gerald      Green  (b)  0  0  0
291    John       Wall  (a)  0  0  0
335    John    Collins  (b)  0  0  0
354  Reggie    Jackson  (b)  0  0  0

In [519]:
fix_row = list(test[test[2].str.contains("(", regex=False)].index)

In [520]:
fix_row

[75, 121, 200, 211, 291, 335, 354]

In [521]:
test.iloc[75,2]

'(b)'

In [522]:
for row in fix_row:
    test.iloc[row, 2] = '0'

In [523]:
test[test[2] != '0']

             0         1       2  3      4  5
10   (William)      Tony  Parker  0      0  0
17        Mike    Conley     Jr.  0      0  0
33       Larry     Nance     Jr.  0      0  0
38        Jose      Juan   Barea  0      0  0
130        Luc   Richard    Mbah  a  Moute  0
147        Tim  Hardaway     Jr.  0      0  0
166       Mike  Dunleavy     Jr.  0      0  0
254     Johnny  O'Bryant     III  0      0  0
269      Glenn  Robinson     III  0      0  0
323      Wayne    Selden     Jr.  0      0  0
346       Otto    Porter     Jr.  0      0  0
362    Derrick    Walton     Jr.  0      0  0

In [524]:
test.iloc[10, 0] = 'Tony'
test.iloc[10, 1] = 'Parker'
test.iloc[10, 2] = '0'
test[test[2] != '0']

           0         1      2  3      4  5
17      Mike    Conley    Jr.  0      0  0
33     Larry     Nance    Jr.  0      0  0
38      Jose      Juan  Barea  0      0  0
130      Luc   Richard   Mbah  a  Moute  0
147      Tim  Hardaway    Jr.  0      0  0
166     Mike  Dunleavy    Jr.  0      0  0
254   Johnny  O'Bryant    III  0      0  0
269    Glenn  Robinson    III  0      0  0
323    Wayne    Selden    Jr.  0      0  0
346     Otto    Porter    Jr.  0      0  0
362  Derrick    Walton    Jr.  0      0  0

In [525]:
test.iloc[17,2] = '0'
test[test[2] != '0']

           0         1      2  3      4  5
33     Larry     Nance    Jr.  0      0  0
38      Jose      Juan  Barea  0      0  0
130      Luc   Richard   Mbah  a  Moute  0
147      Tim  Hardaway    Jr.  0      0  0
166     Mike  Dunleavy    Jr.  0      0  0
254   Johnny  O'Bryant    III  0      0  0
269    Glenn  Robinson    III  0      0  0
323    Wayne    Selden    Jr.  0      0  0
346     Otto    Porter    Jr.  0      0  0
362  Derrick    Walton    Jr.  0      0  0

In [526]:
test.iloc[38,1] = 'Barea'
test.iloc[38,2] = '0'
test[test[2] != '0']

           0         1     2  3      4  5
33     Larry     Nance   Jr.  0      0  0
130      Luc   Richard  Mbah  a  Moute  0
147      Tim  Hardaway   Jr.  0      0  0
166     Mike  Dunleavy   Jr.  0      0  0
254   Johnny  O'Bryant   III  0      0  0
269    Glenn  Robinson   III  0      0  0
323    Wayne    Selden   Jr.  0      0  0
346     Otto    Porter   Jr.  0      0  0
362  Derrick    Walton   Jr.  0      0  0

In [527]:
test.iloc[130,1] = 'Mbaha'
test.iloc[130,2:5] = '0'
test[test[2] != '0']

           0         1    2  3  4  5
33     Larry     Nance  Jr.  0  0  0
147      Tim  Hardaway  Jr.  0  0  0
166     Mike  Dunleavy  Jr.  0  0  0
254   Johnny  O'Bryant  III  0  0  0
269    Glenn  Robinson  III  0  0  0
323    Wayne    Selden  Jr.  0  0  0
346     Otto    Porter  Jr.  0  0  0
362  Derrick    Walton  Jr.  0  0  0

In [528]:
test.iloc[254,2] = '0'
test[test[2] != '0']

           0         1    2  3  4  5
33     Larry     Nance  Jr.  0  0  0
147      Tim  Hardaway  Jr.  0  0  0
166     Mike  Dunleavy  Jr.  0  0  0
269    Glenn  Robinson  III  0  0  0
323    Wayne    Selden  Jr.  0  0  0
346     Otto    Porter  Jr.  0  0  0
362  Derrick    Walton  Jr.  0  0  0

In [529]:
test.iloc[323,2] = '0'
test[test[2] != '0']

           0         1    2  3  4  5
33     Larry     Nance  Jr.  0  0  0
147      Tim  Hardaway  Jr.  0  0  0
166     Mike  Dunleavy  Jr.  0  0  0
269    Glenn  Robinson  III  0  0  0
346     Otto    Porter  Jr.  0  0  0
362  Derrick    Walton  Jr.  0  0  0

In [530]:
test.iloc[346,2] = '0'
test[test[2] != '0']

           0         1    2  3  4  5
33     Larry     Nance  Jr.  0  0  0
147      Tim  Hardaway  Jr.  0  0  0
166     Mike  Dunleavy  Jr.  0  0  0
269    Glenn  Robinson  III  0  0  0
362  Derrick    Walton  Jr.  0  0  0

In [531]:
test.iloc[362,2] = '0'
test[test[2] != '0']
test = test[[0,1,2]]
test

             0                1  2
0         Tony            Allen  0
1         Mike            Scott  0
2        Aaron           Brooks  0
3        Lucas         Nogueira  0
4       Meyers          Leonard  0
5          Ron            Baker  0
6       Rodney          Stuckey  0
7       Jeremy             Lamb  0
8        Brook            Lopez  0
9      Greivis          Vasquez  0
10        Tony           Parker  0
11     Patrick            McCaw  0
12        Dirk         Nowitzki  0
13       Ricky            Rubio  0
14        Doug        McDermott  0
15     Michael  Carter-Williams  0
16        Marc            Gasol  0
17        Mike           Conley  0
18        Alec            Burks  0
19       Boris             Diaw  0
20        Will           Barton  0
21        Joel           Embiid  0
22         Jae          Crowder  0
23      Jarell           Martin  0
24   Christian             Wood  0
25      Wesley         Matthews  0
26      Jeremy              Lin  0
27       Dante       Cunningham  0
28     Anthony         Tolliver  0
29       Lance       Stephenson  0
..         ...              ... ..
386   Channing             Frye  0
387   Antonius        Cleveland  0
388     Daniel            Theis  0
389       Josh             Hart  0
390      Emeka           Okafor  0
391   Terrance         Ferguson  0
392       Cedi            Osman  0
393     Jaylen           Morris  0
394       Kyle            Kuzma  0
395   Domantas          Sabonis  0
396    Timothe           Luwawu  0
397     Tyronn              Lue  0
398    Antonio         Blakeney  0
399    Shabazz           Napier  0
400    Damyean           Dotson  0
401       Kyle          O'Quinn  0
402     Edrice          Adebayo  0
403     Dwight           Powell  0
404      Chris          Boucher  0
405     Wesley           Iwundu  0
406      Frank        Ntilikina  0
407    MarShon           Brooks  0
408     Dwayne            Bacon  0
409       Skal       Labissiere  0
410        Ian            Clark  0
411    Shabazz         Muhammad  0
412       Josh          Jackson  0
413       Alex          Abrines  0
414       Tyus            Jones  0
415      Mason          Plumlee  0

[416 rows x 3 columns]

In [532]:
test.columns = ['first', 'last', 'suffix']
test

         first             last suffix
0         Tony            Allen      0
1         Mike            Scott      0
2        Aaron           Brooks      0
3        Lucas         Nogueira      0
4       Meyers          Leonard      0
5          Ron            Baker      0
6       Rodney          Stuckey      0
7       Jeremy             Lamb      0
8        Brook            Lopez      0
9      Greivis          Vasquez      0
10        Tony           Parker      0
11     Patrick            McCaw      0
12        Dirk         Nowitzki      0
13       Ricky            Rubio      0
14        Doug        McDermott      0
15     Michael  Carter-Williams      0
16        Marc            Gasol      0
17        Mike           Conley      0
18        Alec            Burks      0
19       Boris             Diaw      0
20        Will           Barton      0
21        Joel           Embiid      0
22         Jae          Crowder      0
23      Jarell           Martin      0
24   Christian             Wood      0
25      Wesley         Matthews      0
26      Jeremy              Lin      0
27       Dante       Cunningham      0
28     Anthony         Tolliver      0
29       Lance       Stephenson      0
..         ...              ...    ...
386   Channing             Frye      0
387   Antonius        Cleveland      0
388     Daniel            Theis      0
389       Josh             Hart      0
390      Emeka           Okafor      0
391   Terrance         Ferguson      0
392       Cedi            Osman      0
393     Jaylen           Morris      0
394       Kyle            Kuzma      0
395   Domantas          Sabonis      0
396    Timothe           Luwawu      0
397     Tyronn              Lue      0
398    Antonio         Blakeney      0
399    Shabazz           Napier      0
400    Damyean           Dotson      0
401       Kyle          O'Quinn      0
402     Edrice          Adebayo      0
403     Dwight           Powell      0
404      Chris          Boucher      0
405     Wesley           Iwundu      0
406      Frank        Ntilikina      0
407    MarShon           Brooks      0
408     Dwayne            Bacon      0
409       Skal       Labissiere      0
410        Ian            Clark      0
411    Shabazz         Muhammad      0
412       Josh          Jackson      0
413       Alex          Abrines      0
414       Tyus            Jones      0
415      Mason          Plumlee      0

[416 rows x 3 columns]

In [533]:
first_letter = (test['last'].str[:1]).str.lower() + '/'
first_letter

0      a/
1      s/
2      b/
3      n/
4      l/
5      b/
6      s/
7      l/
8      l/
9      v/
10     p/
11     m/
12     n/
13     r/
14     m/
15     c/
16     g/
17     c/
18     b/
19     d/
20     b/
21     e/
22     c/
23     m/
24     w/
25     m/
26     l/
27     c/
28     t/
29     s/
       ..
386    f/
387    c/
388    t/
389    h/
390    o/
391    f/
392    o/
393    m/
394    k/
395    s/
396    l/
397    l/
398    b/
399    n/
400    d/
401    o/
402    a/
403    p/
404    b/
405    i/
406    n/
407    b/
408    b/
409    l/
410    c/
411    m/
412    j/
413    a/
414    j/
415    p/
Name: last, Length: 416, dtype: object

In [534]:
test = test.assign(letter=first_letter.values)
test

         first             last suffix letter
0         Tony            Allen      0     a/
1         Mike            Scott      0     s/
2        Aaron           Brooks      0     b/
3        Lucas         Nogueira      0     n/
4       Meyers          Leonard      0     l/
5          Ron            Baker      0     b/
6       Rodney          Stuckey      0     s/
7       Jeremy             Lamb      0     l/
8        Brook            Lopez      0     l/
9      Greivis          Vasquez      0     v/
10        Tony           Parker      0     p/
11     Patrick            McCaw      0     m/
12        Dirk         Nowitzki      0     n/
13       Ricky            Rubio      0     r/
14        Doug        McDermott      0     m/
15     Michael  Carter-Williams      0     c/
16        Marc            Gasol      0     g/
17        Mike           Conley      0     c/
18        Alec            Burks      0     b/
19       Boris             Diaw      0     d/
20        Will           Barton      0     b/
21        Joel           Embiid      0     e/
22         Jae          Crowder      0     c/
23      Jarell           Martin      0     m/
24   Christian             Wood      0     w/
25      Wesley         Matthews      0     m/
26      Jeremy              Lin      0     l/
27       Dante       Cunningham      0     c/
28     Anthony         Tolliver      0     t/
29       Lance       Stephenson      0     s/
..         ...              ...    ...    ...
386   Channing             Frye      0     f/
387   Antonius        Cleveland      0     c/
388     Daniel            Theis      0     t/
389       Josh             Hart      0     h/
390      Emeka           Okafor      0     o/
391   Terrance         Ferguson      0     f/
392       Cedi            Osman      0     o/
393     Jaylen           Morris      0     m/
394       Kyle            Kuzma      0     k/
395   Domantas          Sabonis      0     s/
396    Timothe           Luwawu      0     l/
397     Tyronn              Lue      0     l/
398    Antonio         Blakeney      0     b/
399    Shabazz           Napier      0     n/
400    Damyean           Dotson      0     d/
401       Kyle          O'Quinn      0     o/
402     Edrice          Adebayo      0     a/
403     Dwight           Powell      0     p/
404      Chris          Boucher      0     b/
405     Wesley           Iwundu      0     i/
406      Frank        Ntilikina      0     n/
407    MarShon           Brooks      0     b/
408     Dwayne            Bacon      0     b/
409       Skal       Labissiere      0     l/
410        Ian            Clark      0     c/
411    Shabazz         Muhammad      0     m/
412       Josh          Jackson      0     j/
413       Alex          Abrines      0     a/
414       Tyus            Jones      0     j/
415      Mason          Plumlee      0     p/

[416 rows x 4 columns]

In [535]:
last_five = (test['last'].str[:5] + test['first'].str[:2]).str.lower() + '01'
last_five

0      allento01
1      scottmi01
2      brookaa01
3      noguelu01
4      leoname01
5      bakerro01
6      stuckro01
7       lambje01
8      lopezbr01
9      vasqugr01
10     parketo01
11     mccawpa01
12     nowitdi01
13     rubiori01
14     mcderdo01
15     cartemi01
16     gasolma01
17     conlemi01
18     burksal01
19      diawbo01
20     bartowi01
21     embiijo01
22     crowdja01
23     martija01
24      woodch01
25     matthwe01
26       linje01
27     cunnida01
28     tollian01
29     stephla01
         ...
386     fryech01
387    clevean01
388    theisda01
389     hartjo01
390    okafoem01
391    fergute01
392    osmance01
393    morrija01
394    kuzmaky01
395    sabondo01
396    luwawti01
397      luety01
398    blakean01
399    napiesh01
400    dotsoda01
401    o'quiky01
402    adebaed01
403    poweldw01
404    bouchch01
405    iwundwe01
406    ntilifr01
407    brookma01
408    bacondw01
409    labissk01
410    clarkia01
411    muhamsh01
412    jacksjo01
413    abrinal01
414    jonesty01
415    plumlma01
Length: 416, dtype: object

In [536]:
test = test.assign(page_id=last_five.values)
test

         first             last suffix letter    page_id
0         Tony            Allen      0     a/  allento01
1         Mike            Scott      0     s/  scottmi01
2        Aaron           Brooks      0     b/  brookaa01
3        Lucas         Nogueira      0     n/  noguelu01
4       Meyers          Leonard      0     l/  leoname01
5          Ron            Baker      0     b/  bakerro01
6       Rodney          Stuckey      0     s/  stuckro01
7       Jeremy             Lamb      0     l/   lambje01
8        Brook            Lopez      0     l/  lopezbr01
9      Greivis          Vasquez      0     v/  vasqugr01
10        Tony           Parker      0     p/  parketo01
11     Patrick            McCaw      0     m/  mccawpa01
12        Dirk         Nowitzki      0     n/  nowitdi01
13       Ricky            Rubio      0     r/  rubiori01
14        Doug        McDermott      0     m/  mcderdo01
15     Michael  Carter-Williams      0     c/  cartemi01
16        Marc            Gasol      0     g/  gasolma01
17        Mike           Conley      0     c/  conlemi01
18        Alec            Burks      0     b/  burksal01
19       Boris             Diaw      0     d/   diawbo01
20        Will           Barton      0     b/  bartowi01
21        Joel           Embiid      0     e/  embiijo01
22         Jae          Crowder      0     c/  crowdja01
23      Jarell           Martin      0     m/  martija01
24   Christian             Wood      0     w/   woodch01
25      Wesley         Matthews      0     m/  matthwe01
26      Jeremy              Lin      0     l/    linje01
27       Dante       Cunningham      0     c/  cunnida01
28     Anthony         Tolliver      0     t/  tollian01
29       Lance       Stephenson      0     s/  stephla01
..         ...              ...    ...    ...        ...
386   Channing             Frye      0     f/   fryech01
387   Antonius        Cleveland      0     c/  clevean01
388     Daniel            Theis      0     t/  theisda01
389       Josh             Hart      0     h/   hartjo01
390      Emeka           Okafor      0     o/  okafoem01
391   Terrance         Ferguson      0     f/  fergute01
392       Cedi            Osman      0     o/  osmance01
393     Jaylen           Morris      0     m/  morrija01
394       Kyle            Kuzma      0     k/  kuzmaky01
395   Domantas          Sabonis      0     s/  sabondo01
396    Timothe           Luwawu      0     l/  luwawti01
397     Tyronn              Lue      0     l/    luety01
398    Antonio         Blakeney      0     b/  blakean01
399    Shabazz           Napier      0     n/  napiesh01
400    Damyean           Dotson      0     d/  dotsoda01
401       Kyle          O'Quinn      0     o/  o'quiky01
402     Edrice          Adebayo      0     a/  adebaed01
403     Dwight           Powell      0     p/  poweldw01
404      Chris          Boucher      0     b/  bouchch01
405     Wesley           Iwundu      0     i/  iwundwe01
406      Frank        Ntilikina      0     n/  ntilifr01
407    MarShon           Brooks      0     b/  brookma01
408     Dwayne            Bacon      0     b/  bacondw01
409       Skal       Labissiere      0     l/  labissk01
410        Ian            Clark      0     c/  clarkia01
411    Shabazz         Muhammad      0     m/  muhamsh01
412       Josh          Jackson      0     j/  jacksjo01
413       Alex          Abrines      0     a/  abrinal01
414       Tyus            Jones      0     j/  jonesty01
415      Mason          Plumlee      0     p/  plumlma01

[416 rows x 5 columns]

In [537]:
test[test['suffix'] != '0']

     first      last suffix letter    page_id
33   Larry     Nance    Jr.     n/  nancela01
147    Tim  Hardaway    Jr.     h/  hardati01
166   Mike  Dunleavy    Jr.     d/  dunlemi01
269  Glenn  Robinson    III     r/  robingl01

In [538]:
test.iloc[33,4] = test.iloc[33,4][:-1] + '2'
test.iloc[147,4] = test.iloc[147,4][:-1] + '2'
test.iloc[166,4] = test.iloc[166,4][:-1] + '2'
test.iloc[269,4] = test.iloc[269,4][:-1] + '2'
test[test['suffix'] != '0']

     first      last suffix letter    page_id
33   Larry     Nance    Jr.     n/  nancela02
147    Tim  Hardaway    Jr.     h/  hardati02
166   Mike  Dunleavy    Jr.     d/  dunlemi02
269  Glenn  Robinson    III     r/  robingl02

In [539]:
test

         first             last suffix letter    page_id
0         Tony            Allen      0     a/  allento01
1         Mike            Scott      0     s/  scottmi01
2        Aaron           Brooks      0     b/  brookaa01
3        Lucas         Nogueira      0     n/  noguelu01
4       Meyers          Leonard      0     l/  leoname01
5          Ron            Baker      0     b/  bakerro01
6       Rodney          Stuckey      0     s/  stuckro01
7       Jeremy             Lamb      0     l/   lambje01
8        Brook            Lopez      0     l/  lopezbr01
9      Greivis          Vasquez      0     v/  vasqugr01
10        Tony           Parker      0     p/  parketo01
11     Patrick            McCaw      0     m/  mccawpa01
12        Dirk         Nowitzki      0     n/  nowitdi01
13       Ricky            Rubio      0     r/  rubiori01
14        Doug        McDermott      0     m/  mcderdo01
15     Michael  Carter-Williams      0     c/  cartemi01
16        Marc            Gasol      0     g/  gasolma01
17        Mike           Conley      0     c/  conlemi01
18        Alec            Burks      0     b/  burksal01
19       Boris             Diaw      0     d/   diawbo01
20        Will           Barton      0     b/  bartowi01
21        Joel           Embiid      0     e/  embiijo01
22         Jae          Crowder      0     c/  crowdja01
23      Jarell           Martin      0     m/  martija01
24   Christian             Wood      0     w/   woodch01
25      Wesley         Matthews      0     m/  matthwe01
26      Jeremy              Lin      0     l/    linje01
27       Dante       Cunningham      0     c/  cunnida01
28     Anthony         Tolliver      0     t/  tollian01
29       Lance       Stephenson      0     s/  stephla01
..         ...              ...    ...    ...        ...
386   Channing             Frye      0     f/   fryech01
387   Antonius        Cleveland      0     c/  clevean01
388     Daniel            Theis      0     t/  theisda01
389       Josh             Hart      0     h/   hartjo01
390      Emeka           Okafor      0     o/  okafoem01
391   Terrance         Ferguson      0     f/  fergute01
392       Cedi            Osman      0     o/  osmance01
393     Jaylen           Morris      0     m/  morrija01
394       Kyle            Kuzma      0     k/  kuzmaky01
395   Domantas          Sabonis      0     s/  sabondo01
396    Timothe           Luwawu      0     l/  luwawti01
397     Tyronn              Lue      0     l/    luety01
398    Antonio         Blakeney      0     b/  blakean01
399    Shabazz           Napier      0     n/  napiesh01
400    Damyean           Dotson      0     d/  dotsoda01
401       Kyle          O'Quinn      0     o/  o'quiky01
402     Edrice          Adebayo      0     a/  adebaed01
403     Dwight           Powell      0     p/  poweldw01
404      Chris          Boucher      0     b/  bouchch01
405     Wesley           Iwundu      0     i/  iwundwe01
406      Frank        Ntilikina      0     n/  ntilifr01
407    MarShon           Brooks      0     b/  brookma01
408     Dwayne            Bacon      0     b/  bacondw01
409       Skal       Labissiere      0     l/  labissk01
410        Ian            Clark      0     c/  clarkia01
411    Shabazz         Muhammad      0     m/  muhamsh01
412       Josh          Jackson      0     j/  jacksjo01
413       Alex          Abrines      0     a/  abrinal01
414       Tyus            Jones      0     j/  jonesty01
415      Mason          Plumlee      0     p/  plumlma01

[416 rows x 5 columns]

In [551]:
link1 = 'https://www.basketball-reference.com/players/' + test['letter'] + test['page_id'] + '/gamelog-advanced/2017/'
link1

0      https://www.basketball-reference.com/players/a...
1      https://www.basketball-reference.com/players/s...
2      https://www.basketball-reference.com/players/b...
3      https://www.basketball-reference.com/players/n...
4      https://www.basketball-reference.com/players/l...
5      https://www.basketball-reference.com/players/b...
6      https://www.basketball-reference.com/players/s...
7      https://www.basketball-reference.com/players/l...
8      https://www.basketball-reference.com/players/l...
9      https://www.basketball-reference.com/players/v...
10     https://www.basketball-reference.com/players/p...
11     https://www.basketball-reference.com/players/m...
12     https://www.basketball-reference.com/players/n...
13     https://www.basketball-reference.com/players/r...
14     https://www.basketball-reference.com/players/m...
15     https://www.basketball-reference.com/players/c...
16     https://www.basketball-reference.com/players/g...
17     https://www.basketball-reference.com/players/c...
18     https://www.basketball-reference.com/players/b...
19     https://www.basketball-reference.com/players/d...
20     https://www.basketball-reference.com/players/b...
21     https://www.basketball-reference.com/players/e...
22     https://www.basketball-reference.com/players/c...
23     https://www.basketball-reference.com/players/m...
24     https://www.basketball-reference.com/players/w...
25     https://www.basketball-reference.com/players/m...
26     https://www.basketball-reference.com/players/l...
27     https://www.basketball-reference.com/players/c...
28     https://www.basketball-reference.com/players/t...
29     https://www.basketball-reference.com/players/s...
                             ...
386    https://www.basketball-reference.com/players/f...
387    https://www.basketball-reference.com/players/c...
388    https://www.basketball-reference.com/players/t...
389    https://www.basketball-reference.com/players/h...
390    https://www.basketball-reference.com/players/o...
391    https://www.basketball-reference.com/players/f...
392    https://www.basketball-reference.com/players/o...
393    https://www.basketball-reference.com/players/m...
394    https://www.basketball-reference.com/players/k...
395    https://www.basketball-reference.com/players/s...
396    https://www.basketball-reference.com/players/l...
397    https://www.basketball-reference.com/players/l...
398    https://www.basketball-reference.com/players/b...
399    https://www.basketball-reference.com/players/n...
400    https://www.basketball-reference.com/players/d...
401    https://www.basketball-reference.com/players/o...
402    https://www.basketball-reference.com/players/a...
403    https://www.basketball-reference.com/players/p...
404    https://www.basketball-reference.com/players/b...
405    https://www.basketball-reference.com/players/i...
406    https://www.basketball-reference.com/players/n...
407    https://www.basketball-reference.com/players/b...
408    https://www.basketball-reference.com/players/b...
409    https://www.basketball-reference.com/players/l...
410    https://www.basketball-reference.com/players/c...
411    https://www.basketball-reference.com/players/m...
412    https://www.basketball-reference.com/players/j...
413    https://www.basketball-reference.com/players/a...
414    https://www.basketball-reference.com/players/j...
415    https://www.basketball-reference.com/players/p...
Length: 416, dtype: object

In [552]:
link1[415]

'https://www.basketball-reference.com/players/p/plumlma01/gamelog-advanced/2017/'

In [553]:
link2 = 'https://www.basketball-reference.com/players/' + test['letter'] + test['page_id'] + '/gamelog-advanced/2018/'
link2

0      https://www.basketball-reference.com/players/a...
1      https://www.basketball-reference.com/players/s...
2      https://www.basketball-reference.com/players/b...
3      https://www.basketball-reference.com/players/n...
4      https://www.basketball-reference.com/players/l...
5      https://www.basketball-reference.com/players/b...
6      https://www.basketball-reference.com/players/s...
7      https://www.basketball-reference.com/players/l...
8      https://www.basketball-reference.com/players/l...
9      https://www.basketball-reference.com/players/v...
10     https://www.basketball-reference.com/players/p...
11     https://www.basketball-reference.com/players/m...
12     https://www.basketball-reference.com/players/n...
13     https://www.basketball-reference.com/players/r...
14     https://www.basketball-reference.com/players/m...
15     https://www.basketball-reference.com/players/c...
16     https://www.basketball-reference.com/players/g...
17     https://www.basketball-reference.com/players/c...
18     https://www.basketball-reference.com/players/b...
19     https://www.basketball-reference.com/players/d...
20     https://www.basketball-reference.com/players/b...
21     https://www.basketball-reference.com/players/e...
22     https://www.basketball-reference.com/players/c...
23     https://www.basketball-reference.com/players/m...
24     https://www.basketball-reference.com/players/w...
25     https://www.basketball-reference.com/players/m...
26     https://www.basketball-reference.com/players/l...
27     https://www.basketball-reference.com/players/c...
28     https://www.basketball-reference.com/players/t...
29     https://www.basketball-reference.com/players/s...
                             ...
386    https://www.basketball-reference.com/players/f...
387    https://www.basketball-reference.com/players/c...
388    https://www.basketball-reference.com/players/t...
389    https://www.basketball-reference.com/players/h...
390    https://www.basketball-reference.com/players/o...
391    https://www.basketball-reference.com/players/f...
392    https://www.basketball-reference.com/players/o...
393    https://www.basketball-reference.com/players/m...
394    https://www.basketball-reference.com/players/k...
395    https://www.basketball-reference.com/players/s...
396    https://www.basketball-reference.com/players/l...
397    https://www.basketball-reference.com/players/l...
398    https://www.basketball-reference.com/players/b...
399    https://www.basketball-reference.com/players/n...
400    https://www.basketball-reference.com/players/d...
401    https://www.basketball-reference.com/players/o...
402    https://www.basketball-reference.com/players/a...
403    https://www.basketball-reference.com/players/p...
404    https://www.basketball-reference.com/players/b...
405    https://www.basketball-reference.com/players/i...
406    https://www.basketball-reference.com/players/n...
407    https://www.basketball-reference.com/players/b...
408    https://www.basketball-reference.com/players/b...
409    https://www.basketball-reference.com/players/l...
410    https://www.basketball-reference.com/players/c...
411    https://www.basketball-reference.com/players/m...
412    https://www.basketball-reference.com/players/j...
413    https://www.basketball-reference.com/players/a...
414    https://www.basketball-reference.com/players/j...
415    https://www.basketball-reference.com/players/p...
Length: 416, dtype: object

In [554]:
link2[415]

'https://www.basketball-reference.com/players/p/plumlma01/gamelog-advanced/2018/'

In [556]:
test = test.assign(url1=link1.values, url2=link2.values)
player_page = test[['first', 'last', 'suffix', 'page_id','url1', 'url2']]
player_page

,first,last,suffix,page_id,url1,url2
0,Tony,Allen,0,allento01,https://www.basketball-reference.com/players/a...,https://www.basketball-reference.com/players/a...
1,Mike,Scott,0,scottmi01,https://www.basketball-reference.com/players/s...,https://www.basketball-reference.com/players/s...
2,Aaron,Brooks,0,brookaa01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
3,Lucas,Nogueira,0,noguelu01,https://www.basketball-reference.com/players/n...,https://www.basketball-reference.com/players/n...
4,Meyers,Leonard,0,leoname01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
5,Ron,Baker,0,bakerro01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
6,Rodney,Stuckey,0,stuckro01,https://www.basketball-reference.com/players/s...,https://www.basketball-reference.com/players/s...
7,Jeremy,Lamb,0,lambje01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
8,Brook,Lopez,0,lopezbr01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
9,Greivis,Vasquez,0,vasqugr01,https://www.basketball-reference.com/players/v...,https://www.basketball-reference.com/players/v...
10,Tony,Parker,0,parketo01,https://www.basketball-reference.com/players/p...,https://www.basketball-reference.com/players/p...
11,Patrick,McCaw,0,mccawpa01,https://www.basketball-reference.com/players/m...,https://www.basketball-reference.com/players/m...
12,Dirk,Nowitzki,0,nowitdi01,https://www.basketball-reference.com/players/n...,https://www.basketball-reference.com/players/n...
13,Ricky,Rubio,0,rubiori01,https://www.basketball-reference.com/players/r...,https://www.basketball-reference.com/players/r...
14,Doug,McDermott,0,mcderdo01,https://www.basketball-reference.com/players/m...,https://www.basketball-reference.com/players/m...
15,Michael,Carter-Williams,0,cartemi01,https://www.basketball-reference.com/players/c...,https://www.basketball-reference.com/players/c...
16,Marc,Gasol,0,gasolma01,https://www.basketball-reference.com/players/g...,https://www.basketball-reference.com/players/g...
17,Mike,Conley,0,conlemi01,https://www.basketball-reference.com/players/c...,https://www.basketball-reference.com/players/c...
18,Alec,Burks,0,burksal01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
19,Boris,Diaw,0,diawbo01,https://www.basketball-reference.com/players/d...,https://www.basketball-reference.com/players/d...
20,Will,Barton,0,bartowi01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
21,Joel,Embiid,0,embiijo01,https://www.basketball-reference.com/players/e...,https://www.basketball-reference.com/players/e...
22,Jae,Crowder,0,crowdja01,https://www.basketball-reference.com/players/c...,https://www.basketball-reference.com/players/c...
23,Jarell,Martin,0,martija01,https://www.basketball-reference.com/players/m...,https://www.basketball-reference.com/players/m...
24,Christian,Wood,0,woodch01,https://www.basketball-reference.com/players/w...,https://www.basketball-reference.com/players/w...
25,Wesley,Matthews,0,matthwe01,https://www.basketball-reference.com/players/m...,https://www.basketball-reference.com/players/m...
26,Jeremy,Lin,0,linje01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
27,Dante,Cunningham,0,cunnida01,https://www.basketball-reference.com/players/c...,https://www.basketball-reference.com/players/c...
28,Anthony,Tolliver,0,tollian01,https://www.basketball-reference.com/players/t...,https://www.basketball-reference.com/players/t...
29,Lance,Stephenson,0,stephla01,https://www.basketball-reference.com/players/s...,https://www.basketball-reference.com/players/s...
...,...,...,...,...,...,...
386,Channing,Frye,0,fryech01,https://www.basketball-reference.com/players/f...,https://www.basketball-reference.com/players/f...
387,Antonius,Cleveland,0,clevean01,https://www.basketball-reference.com/players/c...,https://www.basketball-reference.com/players/c...
388,Daniel,Theis,0,theisda01,https://www.basketball-reference.com/players/t...,https://www.basketball-reference.com/players/t...
389,Josh,Hart,0,hartjo01,https://www.basketball-reference.com/players/h...,https://www.basketball-reference.com/players/h...
390,Emeka,Okafor,0,okafoem01,https://www.basketball-reference.com/players/o...,https://www.basketball-reference.com/players/o...
391,Terrance,Ferguson,0,fergute01,https://www.basketball-reference.com/players/f...,https://www.basketball-reference.com/players/f...
392,Cedi,Osman,0,osmance01,https://www.basketball-reference.com/players/o...,https://www.basketball-reference.com/players/o...
393,Jaylen,Morris,0,morrija01,https://www.basketball-reference.com/players/m...,https://www.basketball-reference.com/players/m...
394,Kyle,Kuzma,0,kuzmaky01,https://www.basketball-reference.com/players/k...,https://www.basketball-reference.com/players/k...
395,Domantas,Sabonis,0,sabondo01,https://www.basketball-reference.com/players/s...,https://www.basketball-reference.com/players/s...
396,Timothe,Luwawu,0,luwawti01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
397,Tyronn,Lue,0,luety01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
398,Antonio,Blakeney,0,blakean01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
399,Shabazz,Napier,0,napiesh01,https://www.basketball-reference.com/players/n...,https://www.basketball-reference.com/players/n...
400,Damyean,Dotson,0,dotsoda01,https://www.basketball-reference.com/players/d...,https://www.basketball-reference.com/players/d...
401,Kyle,O'Quinn,0,o'quiky01,https://www.basketball-reference.com/players/o...,https://www.basketball-reference.com/players/o...
402,Edrice,Adebayo,0,adebaed01,https://www.basketball-reference.com/players/a...,https://www.basketball-reference.com/players/a...
403,Dwight,Powell,0,poweldw01,https://www.basketball-reference.com/players/p...,https://www.basketball-reference.com/players/p...
404,Chris,Boucher,0,bouchch01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
405,Wesley,Iwundu,0,iwundwe01,https://www.basketball-reference.com/players/i...,https://www.basketball-reference.com/players/i...
406,Frank,Ntilikina,0,ntilifr01,https://www.basketball-reference.com/players/n...,https://www.basketball-reference.com/players/n...
407,MarShon,Brooks,0,brookma01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
408,Dwayne,Bacon,0,bacondw01,https://www.basketball-reference.com/players/b...,https://www.basketball-reference.com/players/b...
409,Skal,Labissiere,0,labissk01,https://www.basketball-reference.com/players/l...,https://www.basketball-reference.com/players/l...
410,Ian,Clark,0,clarkia01,https://www.basketball-reference.com/players/c...,https://www.basketball-reference.com/players/c...
411,Shabazz,Muhammad,0,muhamsh01,https://www.basketball-reference.com/players/m...,https://www.basketball-reference.com/players/m...
412,Josh,Jackson,0,jacksjo01,https://www.basketball-reference.com/players/j...,https://www.basketball-reference.com/players/j...
413,Alex,Abrines,0,abrinal01,https://www.basketball-reference.com/players/a...,https://www.basketball-reference.com/players/a...
414,Tyus,Jones,0,jonesty01,https://www.basketball-reference.com/players/j...,https://www.basketball-reference.com/players/j...
415,Mason,Plumlee,0,plumlma01,https://www.basketball-reference.com/players/p...,https://www.basketball-reference.com/players/p...

In [549]:
def get_playerdf(url):
    r = requests.get(url)
    html_doc = r.text
    bsoup = BeautifulSoup(html_doc)
        
    bsoup.findAll('tr', limit=2)
    
    # use getText()to extract the text we need into a list
    headers = [th.getText() for th in bsoup.findAll('tr', limit=2)[0].findAll('th')]
   
    # exclude the first column as we will not need the ranking order from Basketball Reference for the analysis
    headers = headers[1:]
    
    # avoid the first header row
    rows = bsoup.findAll('tr')[1:]
    player_stats = [[td.getText() for td in rows[i].findAll('td')]
            for i in range(len(rows))]
    
    bsoup_df = pd.DataFrame(player_stats, columns = headers)
    
    return bsoup_df

In [570]:
def get_player_name(url):
    r = requests.get(url)
    html_doc = r.text
    bsoup = BeautifulSoup(html_doc)
           
    # use getText()to extract the text we need into a list
    name = [header.getText() for header in bsoup.findAll('h1', limit=2)]
    
    return name

In [571]:
get_player_name('https://www.basketball-reference.com/players/p/plumlma01/gamelog-advanced/2017/')

['Mason Plumlee 2016-17 Advanced Game Log']

In [564]:
player_data_2017 = pd.DataFrame()
type(player_data_2017)

pandas.core.frame.DataFrame

In [573]:
player_data_2017['name']= get_player_name('https://www.basketball-reference.com/players/p/plumlma01/gamelog-advanced/2017/')
player_data_2017

                                      name
0  Mason Plumlee 2016-17 Advanced Game Log

In [558]:
tony_allen = get_playerdf(player_page['url1'][0])
tony_allen

,G,Date,Age,Tm,,Opp,,GS,MP,TS%,...,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,ORtg,DRtg,GmSc
0,,2016-10-26,34-289,MEM,,MIN,W (+4),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
1,,2016-10-29,34-292,MEM,@,NYK,L (-7),Did Not Dress,None,None,...,None,None,None,None,None,None,None,None,None,None
2,,2016-10-30,34-293,MEM,,WAS,W (+9),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
3,1,2016-11-01,34-295,MEM,@,MIN,L (-36),0,18:39,.286,...,0.0,12.6,0.0,5.3,0.0,12.5,19.1,72,119,2.9
4,2,2016-11-02,34-296,MEM,,NOP,W (+6),1,27:40,.196,...,4.4,6.0,6.2,3.7,0.0,16.4,19.5,48,82,-2.0
5,3,2016-11-04,34-298,MEM,,LAC,L (-11),1,19:09,.286,...,10.9,7.9,9.6,2.6,0.0,12.5,18.0,63,104,0.7
6,4,2016-11-06,34-300,MEM,,POR,L (-6),1,22:08,.814,...,29.3,18.7,0.0,9.5,0.0,12.9,15.6,151,92,13.8
7,,2016-11-08,34-302,MEM,,DEN,W (+1),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
8,,2016-11-12,34-306,MEM,@,MIL,L (-10),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
9,,2016-11-14,34-308,MEM,@,UTA,W (+6),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
10,,2016-11-16,34-310,MEM,@,LAC,W (+4),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
11,5,2016-11-18,34-312,MEM,@,DAL,W (+16),0,18:10,.854,...,5.2,8.5,0.0,6.1,5.5,0.0,18.0,174,66,11.2
12,6,2016-11-19,34-313,MEM,,MIN,W (+22),1,19:54,.250,...,6.3,3.0,0.0,2.9,5.7,11.1,21.3,51,83,0.2
13,7,2016-11-21,34-315,MEM,@,CHO,W (+15),1,31:27,.607,...,10.9,7.7,4.7,3.4,7.3,9.2,16.4,113,95,10.4
14,8,2016-11-23,34-317,MEM,@,PHI,W (+5),1,22:47,.431,...,11.3,7.5,18.3,0.0,0.0,8.7,23.4,88,95,3.7
15,9,2016-11-25,34-319,MEM,,MIA,L (-9),1,23:32,.286,...,4.5,6.4,8.2,0.0,7.6,30.0,18.7,54,106,0.7
16,10,2016-11-26,34-320,MEM,@,MIA,W (+3),1,34:07,.511,...,28.1,15.4,9.0,1.6,2.8,0.0,16.2,108,114,10.2
17,11,2016-11-28,34-322,MEM,,CHO,L (-19),1,20:57,.533,...,10.7,10.3,0.0,4.7,4.1,19.2,22.4,90,101,7.3
18,12,2016-11-30,34-324,MEM,@,TOR,L (-15),1,29:20,.588,...,0.0,9.0,11.1,1.8,0.0,22.7,20.1,111,139,8.2
19,13,2016-12-01,34-325,MEM,,ORL,W (+1),1,27:11,.379,...,9.3,13.1,0.0,5.7,0.0,7.8,22.4,87,97,7.1
20,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
21,14,2016-12-03,34-327,MEM,,LAL,W (+3),1,23:51,.571,...,28.1,20.8,18.3,4.4,0.0,30.0,19.1,98,101,7.7
22,15,2016-12-05,34-329,MEM,@,NOP,W (+2),1,41:30,.638,...,23.3,15.8,0.0,2.5,2.1,11.8,18.5,116,93,17.8
23,16,2016-12-06,34-330,MEM,,PHI,W (+5),1,26:34,.571,...,14.5,7.4,14.0,3.7,0.0,20.2,15.6,94,90,7.1
24,17,2016-12-08,34-332,MEM,,POR,W (+2),1,28:40,.615,...,15.0,15.2,8.0,3.5,0.0,0.0,18.2,140,87,16.5
25,18,2016-12-10,34-334,MEM,,GSW,W (+21),1,38:26,.690,...,10.9,5.6,4.3,1.3,2.5,17.9,19.1,113,95,13.6
26,19,2016-12-13,34-337,MEM,@,CLE,L (-17),1,24:41,.424,...,4.6,2.2,7.1,6.1,0.0,9.6,18.9,80,103,4.7
27,20,2016-12-14,34-338,MEM,,CLE,W (+8),1,32:45,.417,...,9.2,12.5,5.9,4.9,2.9,9.4,29.9,92,89,10.9
28,21,2016-12-16,34-340,MEM,,SAC,L (-4),1,33:55,.512,...,9.0,13.8,6.9,3.1,2.5,11.3,23.6,108,105,14.2
29,22,2016-12-18,34-342,MEM,,UTA,L (-9),1,33:51,.605,...,16.7,12.6,6.4,3.3,0.0,0.0,9.7,143,94,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,47,2017-02-08,35-028,MEM,,PHO,W (+19),1,29:25,.363,...,17.0,13.1,11.5,3.5,2.5,6.8,22.1,89,90,7.2
57,48,2017-02-10,35-030,MEM,,GSW,L (-15),1,28:07,.497,...,25.1,19.0,6.7,1.7,3.9,6.2,22.6,117,121,12.3
58,,2017-02-13,35-033,MEM,@,BRK,W (+9),Did Not Dress,None,None,...,None,None,None,None,None,None,None,None,None,None
59,49,2017-02-15,35-035,MEM,,NOP,L (-4),1,18:59,.000,...,13.0,8.8,7.7,0.0,0.0,42.9,15.4,15,106,-4.6
60,50,2017-02-24,35-044,MEM,@,IND,L (-10),1,25:29,.611,...,26.9,14.8,14.7,10.4,0.0,30.8,23.3,88,94,10.0
61,51,2017-02-26,35-046,MEM,@,DEN,W (+7),1,27:56,.450,...,11.2,13.7,0.0,9.4,3.4,31.1,20.9,79,90,7.4
62,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
63,52,2017-02-28,35-048,MEM,,PHO,W (+18),1,26:54,.698,...,10.2,10.1,4.6,1.9,0.0,20.2,16.2,121,119,9.0
64,53,2017-03-03,35-051,MEM,@,DAL,L (-4),1,22:07,.583,...,10.9,5.2,0.0,2.3,0.0,14.3,14.9,96,111,4.6
65,54,2017-03-04,35-052,MEM,@,HOU,L (-15),1,27:01,.500,...,13.7,12.0,10.4,0.0,0.0,0.0,16.4,125,133,8.5
66,55,2017-03-06,35-054,MEM,,BRK,L (-13),0,16:44,.512,...,8.0,11.0,10.1,5.9,0.0,29.1,18.1,90,116,4.2
67,56,2017-03-09,35-057,MEM,,LAC,L (-16),0,23:56,.507,...,11.5,5.0,27.7,2.1,0.0,0.0,17.5,113,120,8.2
68,57,2017-03-11,35-059,MEM,,ATL,L (-17),0,21:05,.286,...,13.4,13.1,23.2,0.0,0.0,22.2,18.1,71,120,2.3
69,58,2017-03-13,35-061,MEM,,MIL,W (+20),1,29:33,.663,...,14.3,9.4,5.2,0.0,0.0,15.0,21.4,111,117,9.1
70,59,2017-03-15,35-063,MEM,@,CHI,W (+7),1,23:52,.460,...,11.6,12.4,21.6,0.0,0.0,0.0,21.1,123,110,8.9
71,60,2017-03-16,35-064,MEM,@,ATL,W (+12),1,28:00,.563,...,8.6,12.0,5.3,3.7,0.0,10.1,15.3,120,98,9.1
72,61,2017-03-18,35-066,MEM,,SAS,W (+8),1,30:44,.368,...,16.9,14.2,0.0,0.0,6.6,0.0,17.1,92,108,4.9
73,,2017-03-21,35-069,MEM,@,NOP,L (-13),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
74,62,2017-03-23,35-071,MEM,@,SAS,L (-7),1,28:39,.444,...,13.2,8.7,12.3,3.9,3.3,0.0,15.4,108,106,7.8
75,63,2017-03-26,35-074,MEM,@,GSW,L (-12),1,30:27,.450,...,10.2,12.8,24.9,3.6,0.0,25.3,17.9,95,119,8.3
76,64,2017-03-27,35-075,MEM,@,SAC,L (-1),1,19:09,.429,...,29.5,21.7,0.0,3.1,0.0,12.5,18.3,96,104,4.8
77,65,2017-03-29,35-077,MEM,,IND,W (+13),1,33:30,.298,...,9.3,13.3,15.0,0.0,0.0,7.8,17.6,97,114,5.8
78,66,2017-03-31,35-079,MEM,,DAL,W (+9),1,26:57,.222,...,11.9,10.5,5.7,2.0,0.0,0.0,16.6,69,103,0.9
79,67,2017-04-02,35-081,MEM,@,LAL,L (-5),1,32:41,.813,...,26.1,15.7,14.1,3.2,2.2,11.1,13.2,144,108,15.5
80,,2017-04-04,35-083,MEM,@,SAS,L (-6),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
81,68,2017-04-05,35-084,MEM,,OKC,L (-3),1,27:48,.700,...,16.1,14.7,27.7,3.8,0.0,16.7,20.7,130,107,14.3
82,69,2017-04-07,35-086,MEM,,NYK,W (+13),1,19:28,.625,...,10.7,12.5,0.0,0.0,0.0,0.0,21.4,135,112,8.0
83,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
84,70,2017-04-09,35-088,MEM,,DET,L (-13),1,20:10,.425,...,18.3,12.5,15.2,5.4,0.0,0.0,14.6,108,109,6.9
85,71,2017-04-12,35-091,MEM,,DAL,L (-7),1,5:50,.500,...,0.0,19.4,0.0,0.0,0.0,0.0,30.6,122,120,3.4

In [559]:
mike_scott =  get_playerdf(player_page['url1'][1])
mike_scott

,G,Date,Age,Tm,,Opp,,GS,MP,TS%,...,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,ORtg,DRtg,GmSc
0,,2016-10-27,28-103,ATL,,WAS,W (+15),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
1,,2016-10-29,28-105,ATL,@,PHI,W (+32),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
2,,2016-10-31,28-107,ATL,,SAC,W (+11),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
3,,2016-11-02,28-109,ATL,,LAL,L (-7),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
4,,2016-11-04,28-111,ATL,@,WAS,L (-3),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
5,,2016-11-05,28-112,ATL,,HOU,W (+15),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
6,,2016-11-08,28-115,ATL,@,CLE,W (+4),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
7,,2016-11-09,28-116,ATL,,CHI,W (+8),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
8,,2016-11-12,28-119,ATL,,PHI,W (+21),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
9,,2016-11-15,28-122,ATL,@,MIA,W (+3),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
10,,2016-11-16,28-123,ATL,,MIL,W (+7),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
11,,2016-11-18,28-125,ATL,@,CHO,L (-4),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
12,,2016-11-20,28-127,ATL,@,NYK,L (-10),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
13,,2016-11-22,28-129,ATL,,NOP,L (-18),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
14,,2016-11-23,28-130,ATL,@,IND,W (+11),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
15,,2016-11-25,28-132,ATL,@,UTA,L (-27),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
16,,2016-11-27,28-134,ATL,@,LAL,L (-15),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
17,,2016-11-28,28-135,ATL,@,GSW,L (-5),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
18,1,2016-11-30,28-137,ATL,@,PHO,L (-2),0,3:37,.000,...,28.9,16.4,0.0,0.0,0.0,50.0,23.4,0,109,-1.4
19,2,2016-12-02,28-139,ATL,,DET,L (-36),0,11:32,.250,...,22.5,14.5,44.9,0.0,0.0,20.0,20.0,69,128,1.6
20,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
21,3,2016-12-03,28-140,ATL,@,TOR,L (-44),0,12:36,.000,...,41.2,17.7,32.7,0.0,0.0,0.0,13.6,40,132,0.5
22,,2016-12-05,28-142,ATL,,OKC,L (-3),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
23,,2016-12-07,28-144,ATL,,MIA,W (+8),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
24,,2016-12-09,28-146,ATL,@,MIL,W (+4),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
25,,2016-12-13,28-150,ATL,,ORL,L (-11),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
26,,2016-12-16,28-153,ATL,@,TOR,W (+4),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
27,,2016-12-17,28-154,ATL,,CHO,L (-8),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
28,4,2016-12-19,28-156,ATL,@,OKC,W (+2),0,7:33,.625,...,14.1,16.1,0.0,0.0,0.0,0.0,25.3,127,119,4.0
29,5,2016-12-21,28-158,ATL,,MIN,L (-8),0,18:03,.410,...,6.3,12.2,0.0,0.0,0.0,0.0,13.3,112,115,3.6
30,6,2016-12-23,28-160,ATL,@,DEN,W (+1),0,11:43,.434,...,32.3,19.1,37.4,4.2,0.0,0.0,21.7,118,104,6.5
31,7,2016-12-26,28-163,ATL,@,MIN,L (-14),0,17:31,.417,...,20.6,9.6,9.3,3.0,5.4,14.3,17.5,86,110,3.9
32,,2016-12-28,28-165,ATL,,NYK,W (+4),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
33,,2016-12-30,28-167,ATL,,DET,W (+7),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
34,,2017-01-01,28-169,ATL,,SAS,W (+2),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
35,,2017-01-04,28-172,ATL,@,ORL,W (+19),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
36,,2017-01-05,28-173,ATL,@,NOP,W (+5),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
37,,2017-01-07,28-175,ATL,@,DAL,W (+15),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
38,8,2017-01-10,28-178,ATL,@,BRK,W (+20),0,3:37,,...,0.0,0.0,0.0,0.0,0.0,,0.0,0,108,-0.8
39,,2017-01-13,28-181,ATL,,BOS,L (-2),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
40,,2017-01-15,28-183,ATL,,MIL,W (+13),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
41,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
42,9,2017-01-16,28-184,ATL,@,NYK,W (+1),0,9:33,.300,...,11.7,11.3,14.4,0.0,0.0,0.0,23.5,84,117,1.6
43,10,2017-01-18,28-186,ATL,@,DET,L (-23),0,14:00,.000,...,16.3,7.5,0.0,0.0,0.0,25.0,12.9,0,125,-2.5
44,11,2017-01-20,28-188,ATL,,CHI,W (+9),0,20:59,.400,...,10.9,5.6,26.6,2.3,0.0,16.7,12.6,96,100,4.3
45,12,2017-01-21,28-189,ATL,,PHI,W (+17),0,5:38,.000,...,19.8,9.9,0.0,0.0,0.0,0.0,14.9,0,98,-1.5
46,13,2017-01-23,28-191,ATL,,LAC,L (-10),0,4:22,.000,...,0.0,0.0,0.0,0.0,0.0,50.0,20.5,0,129,-2.5
47,,2017-01-25,28-193,ATL,@,CHI,W (+5),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
48,14,2017-01-27,28-195,ATL,,WAS,L (-26),0,10:45,.799,...,29.1,19.2,0.0,4.4,7.7,12.7,31.1,131,97,10.3
49,,2017-01-29,28-197,ATL,,NYK,W (+3),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
50,15,2017-02-01,28-200,ATL,@,MIA,L (-23),0,13:46,.000,...,7.9,3.9,0.0,0.0,5.7,0.0,12.7,0,119,-2.2
51,,2017-02-02,28-201,ATL,@,HOU,W (+5),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
52,16,2017-02-04,28-203,ATL,,ORL,W (+27),0,5:23,.333,...,0.0,11.0,0.0,0.0,0.0,0.0,25.5,93,102,0.6
53,17,2017-02-06,28-205,ATL,,UTA,L (-25),0,12:00,1.000,...,25.0,16.2,13.8,0.0,0.0,0.0,4.0,207,135,3.7
54,,2017-02-08,28-207,ATL,,DEN,W (+11),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
55,,2017-02-10,28-209,ATL,@,SAC,L (-1),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
56,,2017-02-13,28-212,ATL,@,POR,W (+5),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
57,18,2017-02-15,28-214,ATL,@,LAC,L (-15),0,12:20,.500,...,0.0,0.0,13.8,0.0,0.0,33.3,10.9,74,110,0.7

In [562]:
tony_allen.append(mike_scott).head(50)

,G,Date,Age,Tm,,Opp,,GS,MP,TS%,...,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,ORtg,DRtg,GmSc
0,,2016-10-26,34-289,MEM,,MIN,W (+4),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
1,,2016-10-29,34-292,MEM,@,NYK,L (-7),Did Not Dress,None,None,...,None,None,None,None,None,None,None,None,None,None
2,,2016-10-30,34-293,MEM,,WAS,W (+9),Did Not Play,None,None,...,None,None,None,None,None,None,None,None,None,None
3,1,2016-11-01,34-295,MEM,@,MIN,L (-36),0,18:39,.286,...,0.0,12.6,0.0,5.3,0.0,12.5,19.1,72,119,2.9
4,2,2016-11-02,34-296,MEM,,NOP,W (+6),1,27:40,.196,...,4.4,6.0,6.2,3.7,0.0,16.4,19.5,48,82,-2.0
5,3,2016-11-04,34-298,MEM,,LAC,L (-11),1,19:09,.286,...,10.9,7.9,9.6,2.6,0.0,12.5,18.0,63,104,0.7
6,4,2016-11-06,34-300,MEM,,POR,L (-6),1,22:08,.814,...,29.3,18.7,0.0,9.5,0.0,12.9,15.6,151,92,13.8
7,,2016-11-08,34-302,MEM,,DEN,W (+1),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
8,,2016-11-12,34-306,MEM,@,MIL,L (-10),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
9,,2016-11-14,34-308,MEM,@,UTA,W (+6),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
10,,2016-11-16,34-310,MEM,@,LAC,W (+4),Inactive,None,None,...,None,None,None,None,None,None,None,None,None,None
11,5,2016-11-18,34-312,MEM,@,DAL,W (+16),0,18:10,.854,...,5.2,8.5,0.0,6.1,5.5,0.0,18.0,174,66,11.2
12,6,2016-11-19,34-313,MEM,,MIN,W (+22),1,19:54,.250,...,6.3,3.0,0.0,2.9,5.7,11.1,21.3,51,83,0.2
13,7,2016-11-21,34-315,MEM,@,CHO,W (+15),1,31:27,.607,...,10.9,7.7,4.7,3.4,7.3,9.2,16.4,113,95,10.4
14,8,2016-11-23,34-317,MEM,@,PHI,W (+5),1,22:47,.431,...,11.3,7.5,18.3,0.0,0.0,8.7,23.4,88,95,3.7
15,9,2016-11-25,34-319,MEM,,MIA,L (-9),1,23:32,.286,...,4.5,6.4,8.2,0.0,7.6,30.0,18.7,54,106,0.7
16,10,2016-11-26,34-320,MEM,@,MIA,W (+3),1,34:07,.511,...,28.1,15.4,9.0,1.6,2.8,0.0,16.2,108,114,10.2
17,11,2016-11-28,34-322,MEM,,CHO,L (-19),1,20:57,.533,...,10.7,10.3,0.0,4.7,4.1,19.2,22.4,90,101,7.3
18,12,2016-11-30,34-324,MEM,@,TOR,L (-15),1,29:20,.588,...,0.0,9.0,11.1,1.8,0.0,22.7,20.1,111,139,8.2
19,13,2016-12-01,34-325,MEM,,ORL,W (+1),1,27:11,.379,...,9.3,13.1,0.0,5.7,0.0,7.8,22.4,87,97,7.1
20,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
21,14,2016-12-03,34-327,MEM,,LAL,W (+3),1,23:51,.571,...,28.1,20.8,18.3,4.4,0.0,30.0,19.1,98,101,7.7
22,15,2016-12-05,34-329,MEM,@,NOP,W (+2),1,41:30,.638,...,23.3,15.8,0.0,2.5,2.1,11.8,18.5,116,93,17.8
23,16,2016-12-06,34-330,MEM,,PHI,W (+5),1,26:34,.571,...,14.5,7.4,14.0,3.7,0.0,20.2,15.6,94,90,7.1
24,17,2016-12-08,34-332,MEM,,POR,W (+2),1,28:40,.615,...,15.0,15.2,8.0,3.5,0.0,0.0,18.2,140,87,16.5
25,18,2016-12-10,34-334,MEM,,GSW,W (+21),1,38:26,.690,...,10.9,5.6,4.3,1.3,2.5,17.9,19.1,113,95,13.6
26,19,2016-12-13,34-337,MEM,@,CLE,L (-17),1,24:41,.424,...,4.6,2.2,7.1,6.1,0.0,9.6,18.9,80,103,4.7
27,20,2016-12-14,34-338,MEM,,CLE,W (+8),1,32:45,.417,...,9.2,12.5,5.9,4.9,2.9,9.4,29.9,92,89,10.9
28,21,2016-12-16,34-340,MEM,,SAC,L (-4),1,33:55,.512,...,9.0,13.8,6.9,3.1,2.5,11.3,23.6,108,105,14.2
29,22,2016-12-18,34-342,MEM,,UTA,L (-9),1,33:51,.605,...,16.7,12.6,6.4,3.3,0.0,0.0,9.7,143,94,11.6
30,23,2016-12-20,34-344,MEM,,BOS,L (-3),1,37:35,.625,...,9.8,12.1,0.0,1.4,3.2,0.0,9.5,147,117,11.7
31,24,2016-12-21,34-345,MEM,@,DET,W (+12),1,28:02,.375,...,4.2,4.1,11.5,1.9,0.0,11.1,15.7,81,100,2.4
32,25,2016-12-23,34-347,MEM,,HOU,W (+6),1,28:48,.666,...,8.5,8.5,9.3,3.6,4.5,12.9,12.7,133,115,10.6
33,26,2016-12-26,34-350,MEM,@,ORL,L (-10),1,22:47,.635,...,10.5,5.4,0.0,2.3,0.0,0.0,17.6,124,123,7.1
34,27,2016-12-27,34-351,MEM,@,BOS,L (-10),1,34:56,.704,...,10.8,11.5,4.8,5.8,0.0,7.6,16.1,142,116,18.1
35,28,2016-12-29,34-353,MEM,,OKC,W (+34),1,30:39,.400,...,14.9,18.1,4.3,3.5,0.0,33.3,22.9,77,87,3.4
36,29,2016-12-31,34-355,MEM,@,SAC,W (+14),1,21:09,.786,...,11.6,11.5,7.0,2.7,0.0,0.0,16.2,170,117,11.4
37,30,2017-01-03,34-358,MEM,@,LAL,L (-14),1,24:06,.820,...,13.9,9.7,16.6,2.1,0.0,38.1,15.3,103,123,7.0
38,31,2017-01-04,34-359,MEM,@,LAC,L (-9),1,29:49,.630,...,16.5,11.0,10.7,0.0,3.2,8.8,16.9,127,122,10.8
39,32,2017-01-06,34-361,MEM,@,GSW,W (+9),1,47:34,.326,...,16.7,14.7,7.5,6.3,0.0,10.6,17.1,89,103,12.3
40,33,2017-01-08,34-363,MEM,,UTA,W (+9),1,23:06,.333,...,19.3,13.0,13.0,2.4,0.0,57.1,15.0,48,89,0.2
41,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
42,34,2017-01-11,35-000,MEM,@,OKC,L (-8),1,22:24,.200,...,5.8,4.7,12.0,2.2,0.0,0.0,9.6,72,112,1.1
43,35,2017-01-13,35-002,MEM,@,HOU,W (+5),1,24:33,.814,...,16.6,10.3,25.1,2.0,0.0,18.2,29.4,129,107,15.9
44,36,2017-01-15,35-004,MEM,,CHI,L (-4),1,33:15,.250,...,20.1,11.9,15.6,4.5,2.4,27.3,14.3,64,102,4.7
45,37,2017-01-18,35-007,MEM,@,WAS,L (-3),1,29:48,.342,...,8.1,12.5,5.4,3.6,0.0,18.6,15.8,85,116,3.5
46,38,2017-01-20,35-009,MEM,,SAC,W (+16),1,30:32,.547,...,16.4,16.9,0.0,0.0,0.0,7.8,18.6,120,102,10.5
47,39,2017-01-21,35-010,MEM,,HOU,L (-24),1,24:35,.000,...,11.8,9.0,11.8,8.2,0.0,25.0,13.8,28,113,1.2
48,40,2017-01-25,35-014,MEM,,TOR,W (+2),1,34:48,.519,...,22.5,16.9,5.2,0.0,4.8,12.2,23.1,101,107,11.0
49,41,2017-01-27,35-016,MEM,@,POR,L (-3),1,35:08,.170,...,23.9,12.8,3.8,4.5,0.0,33.8,11.8,30,116,-0.7